services:
  - type: web
    name: kiosk-admin
    runtime: node
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma migrate deploy && npm run build
    startCommand: npm run start
    autoDeployTrigger: commit
